### ISSUE TITLE
Would be nice to publish a nuget package

### ISSUE THREAD

**Issue by Zaid-Ajaj** [davedawkins/Fable.React.DrawingCanvas#1]
Hi @davedawkins, awesome stuff you got here 🚀 I was wondering if you have plans on publishing a nuget package from it, that would be nice so that people could start playing with it more 😄

**Comment by davedawkins** [comment]
Hi @Zaid-Ajaj , thanks for checking this out. Yes, I'll make a package tonight

**Comment by davedawkins** [comment]
@Zaid-Ajaj https://www.nuget.org/packages/Fable.React.DrawingCanvas

**Comment by Zaid-Ajaj** [comment]
Great! I will give it a try as soon as time permits 💯
