### ISSUE TITLE
Upgrade to newest Fable

### ISSUE THREAD

**Issue by jwosty** [davedawkins/Fable.React.DrawingCanvas#7]
I'm getting the following compilation error:

```
7>FSC: Error FS0193 : The module/namespace 'Fable.React' from compilation unit 'Fable.React' did not contain the namespace, module or type 'ReactElement'
```

I believe this is just because the library needs to be updated to depend on the latest version of Fable and Fable.React. See: https://github.com/fable-compiler/fable-react/issues/210 https://github.com/fable-compiler/fable-react/pull/208

There were similar issues on various other libraries; can't find it right now but I'm pretty certain this is the only problem.

**Comment by davedawkins** [comment]
Hi, 
I've almost finished bringing this up to date, and will commit my changes either today or tomorrow. Thanks for the report.

**Comment by davedawkins** [comment]
Hi,
I've published v1.3 on nuget, and commited my changes. I've updated to latest Fable, and to latest React. I've updated all the examples, and deleted a bunch of obsolete babel stuff. Can you see if this fixes the issue for you?

**Comment by jwosty** [comment]
It seems that Fable.React.DrawingCanvas 1.3.0 has a version constraint set for Fable.React = 7.0.1 (see https://www.nuget.org/packages/Fable.React.DrawingCanvas/1.3.0). Should be Fable.React >= 9.0

**Comment by davedawkins** [comment]
Thanks for this. I can update the paket.dependency and repackage

**Comment by davedawkins** [comment]
1.3.1 commited and pushed to nuget
